version: "3"

services:
  selenium:
    image: selenium/standalone-chrome
    networks:
      - selenium_test_network
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - selenium
    environment:
        SELENIUM_HOST: selenium
    networks:
      - selenium_test_network
networks:
  selenium_test_network:
